ALTER TABLE "Profile" ADD COLUMN "tags" TEXT;
ALTER TABLE "Profile" ADD COLUMN "ownerMemberId" INTEGER;
ALTER TABLE "Profile" ADD COLUMN "assignedMemberId" INTEGER;
ALTER TABLE "Profile" ADD COLUMN "lastUsedAt" DATETIME;
ALTER TABLE "Profile" ADD COLUMN "launchCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Profile" ADD COLUMN "browserCore" TEXT;
ALTER TABLE "Profile" ADD COLUMN "browserVersion" TEXT;
ALTER TABLE "Profile" ADD COLUMN "os" TEXT;
ALTER TABLE "Profile" ADD COLUMN "osVersion" TEXT;
ALTER TABLE "Profile" ADD COLUMN "userAgent" TEXT DEFAULT 'Auto';
ALTER TABLE "Profile" ADD COLUMN "startupUrls" TEXT;
ALTER TABLE "Profile" ADD COLUMN "platformAccounts" TEXT;
ALTER TABLE "Profile" ADD COLUMN "webrtc" TEXT;
ALTER TABLE "Profile" ADD COLUMN "timezoneType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "timezoneCustom" TEXT;
ALTER TABLE "Profile" ADD COLUMN "locationType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "locationPrompt" TEXT;
ALTER TABLE "Profile" ADD COLUMN "locationLat" TEXT;
ALTER TABLE "Profile" ADD COLUMN "locationLng" TEXT;
ALTER TABLE "Profile" ADD COLUMN "locationAcc" TEXT;
ALTER TABLE "Profile" ADD COLUMN "languageType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "languageCustom" TEXT;
ALTER TABLE "Profile" ADD COLUMN "displayLangType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "displayLangCustom" TEXT;
ALTER TABLE "Profile" ADD COLUMN "resolutionType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "resolutionW" TEXT;
ALTER TABLE "Profile" ADD COLUMN "resolutionH" TEXT;
ALTER TABLE "Profile" ADD COLUMN "fontsType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "canvasNoise" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Profile" ADD COLUMN "webglImageNoise" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Profile" ADD COLUMN "audioContextNoise" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Profile" ADD COLUMN "clientRectsNoise" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Profile" ADD COLUMN "speechVoicesNoise" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Profile" ADD COLUMN "mediaDevice" TEXT;
ALTER TABLE "Profile" ADD COLUMN "webglMetadata" TEXT;
ALTER TABLE "Profile" ADD COLUMN "webglVendor" TEXT;
ALTER TABLE "Profile" ADD COLUMN "webglRenderer" TEXT;
ALTER TABLE "Profile" ADD COLUMN "webgpu" TEXT;
ALTER TABLE "Profile" ADD COLUMN "cpuType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "cpuCores" TEXT;
ALTER TABLE "Profile" ADD COLUMN "ramType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "ramGb" TEXT;
ALTER TABLE "Profile" ADD COLUMN "deviceNameType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "deviceName" TEXT;
ALTER TABLE "Profile" ADD COLUMN "macAddressType" TEXT;
ALTER TABLE "Profile" ADD COLUMN "macAddress" TEXT;
ALTER TABLE "Profile" ADD COLUMN "doNotTrack" TEXT;
ALTER TABLE "Profile" ADD COLUMN "portScanProtection" TEXT;
ALTER TABLE "Profile" ADD COLUMN "hardwareAcceleration" TEXT;
ALTER TABLE "Profile" ADD COLUMN "disableTls" TEXT;
ALTER TABLE "Profile" ADD COLUMN "launchArgs" TEXT;
ALTER TABLE "Profile" ADD COLUMN "advancedExt" TEXT;
ALTER TABLE "Profile" ADD COLUMN "advancedSync" TEXT;
ALTER TABLE "Profile" ADD COLUMN "syncItemsJson" TEXT;
ALTER TABLE "Profile" ADD COLUMN "advancedBrowser" TEXT;
ALTER TABLE "Profile" ADD COLUMN "browserSettingsJson" TEXT;
ALTER TABLE "Profile" ADD COLUMN "randomFingerprint" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Profile" ADD COLUMN "updatedAt" DATETIME;
